# Changing the server port
server:
  port: 8081


# DB specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#   password: root


# ORM s/w specific properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# Spring
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


# To accept case insensitive enums in request body
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true


# Swagger ui
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  version: 2.6.7



